# Ref: https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner
name: Markdown Sample

# Pipeline triggers
on:
  push:
  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches-ignore:
      - main

# Define jobs to run in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        run: |
          pwd
          ls -l
          docker run -v $PWD/README.md:/app/README.md -w /app pipelinecomponents/markdownlint README.md
      # TODO Set up AWS credentials (use Github secrets as environment variables)
      - run: echo "Run commands here"
      # TODO Shell into the EC2 instance, upload the file, and restart service
      - run: echo "Run commands here"
