name: Markdown Sample

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        run: |
          pwd
          ls -l
          env | grep GITHUB
          #docker run -v $PWD/README.md:/app/README.md -w /app pipelinecomponents/markdownlint README.md

  deploy:
    runs-on: ubuntu-latest
    steps:
      # TODO Set up AWS credentials (use Github secrets as environment variables)
      - run: echo "Run commands here"
      # TODO Shell into the EC2 instance, upload the file, and restart service
      - run: echo "Run commands here"
