name: Workflow Main

on:
  workflow_dispatch:

jobs:
  #call-workflow:
    #uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: diegoaojeda/sandbox/.github/workflows/workflow-child1.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
