name: Workflow Main

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: diegoaojeda/sandbox/.github/workflows/workflow-child1.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
